/* 
 * Copyright (c) 2017, CareEvolution Inc (info@careevolution.com)
 * 
 * This file is licensed under the MIT License - see License.txt
 */

var SMARTestRegistrations = [
	{
		name: "Epic Test",
		clientID: "44d7c35a-f6e7-4481-8b69-31d4d8017f03",
		scope: "ALLERGYINTOLERANCE.READ ALLERGYINTOLERANCE.SEARCH BINARY.READ CAREPLAN.READ CAREPLAN.SEARCH CONDITION.READ CONDITION.SEARCH DEVICE.READ DEVICE.SEARCH DIAGNOSTICREPORT.READ DIAGNOSTICREPORT.SEARCH DOCUMENTREFERENCE.READ DOCUMENTREFERENCE.SEARCH GOAL.READ GOAL.SEARCH IMMUNIZATION.READ IMMUNIZATION.SEARCH MEDICATION.READ MEDICATION.SEARCH MEDICATIONORDER.READ MEDICATIONORDER.SEARCH MEDICATIONSTATEMENT.READ MEDICATIONSTATEMENT.SEARCH OBSERVATION.READ OBSERVATION.SEARCH PATIENT.READ PATIENT.SEARCH PRACTITIONER.READ PRACTITIONER.SEARCH PROCEDURE.READ PROCEDURE.SEARCH"
	},
	{
		name: "Epic Production",
		clientID: "d725e093-9fb3-4fb3-8126-8be4b902b19e",
		scope: "ALLERGYINTOLERANCE.READ ALLERGYINTOLERANCE.SEARCH BINARY.READ CAREPLAN.READ CAREPLAN.SEARCH CONDITION.READ CONDITION.SEARCH DEVICE.READ DEVICE.SEARCH DIAGNOSTICREPORT.READ DIAGNOSTICREPORT.SEARCH DOCUMENTREFERENCE.READ DOCUMENTREFERENCE.SEARCH GOAL.READ GOAL.SEARCH IMMUNIZATION.READ IMMUNIZATION.SEARCH MEDICATION.READ MEDICATION.SEARCH MEDICATIONORDER.READ MEDICATIONORDER.SEARCH MEDICATIONSTATEMENT.READ MEDICATIONSTATEMENT.SEARCH OBSERVATION.READ OBSERVATION.SEARCH PATIENT.READ PATIENT.SEARCH PRACTITIONER.READ PRACTITIONER.SEARCH PROCEDURE.READ PROCEDURE.SEARCH"
	}
];
